$(document).ready(function(){$.getJSON("/graph_data.json?uri="+query_string,function(data){if($('#index_reactions-by-reports-graph').length!=0){$('#index_reactions-by-reports-graph').highcharts({chart:{type:'column',zoomType:'xy',backgroundColor:'#F0F0F0'},credits:{enabled:true,text:"Via ResearchAE.com"},title:{text:chart_title+" - by Reaction",style:{width:'300px'}},subtitle:{text:data.ptreaction_count.total_events+' adverse events over '+data.ptreaction_count.total_reports+' adverse event reports | Source: OpenFDA API '+disclaimer},yAxis:{min:0,title:{text:'# Adverse Events'}},xAxis:{type:'category',title:{text:'Reactions'},labels:{enabled:false},minorTickLength:0,tickLength:0},legend:{enabled:false},tooltip:{pointFormat:chart_title+': <b>{point.y}</b>',},series:[{name:'Drug Reactions',data:data.ptreaction_count.data,}],plotOptions:{series:{cursor:'pointer',point:{events:{click:function(){var reactionmeddrapt=this.name
var new_location=location.href
if(location.search==""){new_location+="?"}
new_location+="&reactionmeddrapt="+reactionmeddrapt
location=new_location}}}}},});}
if($('#by-date-graph').length!=0){$('#by-date-graph').highcharts({chart:{type:'area',zoomType:'xy',backgroundColor:'#F0F0F0'},credits:{enabled:true,text:"Via ResearchAE.com"},title:{text:chart_title+" - by Receive Date",style:{width:'300px'}},subtitle:{text:data.ptreaction_count.total_reports+' adverse event reports | Source: OpenFDA API'+disclaimer},yAxis:{min:0,title:{text:'# Adverse Event Reports'}},xAxis:{type:'datetime',title:{text:'Date'},},legend:{enabled:false},series:[{name:'Receive Date',data:data.ptreaction_by_receivedate.data,}],plotOptions:{series:{cursor:'pointer',point:{events:{click:function(){var from_date=new Date(this.x)
var from_date_formatted=from_date.toISOString().split("T")[0]
var new_location=location.href
if(location.search==""){new_location+="?"}
new_location+="&from_date="+from_date_formatted+"&to_date="+from_date_formatted
location=new_location}}}}},});}
if($('#by-date-month-graph').length!=0){$('#by-date-month-graph').highcharts({chart:{type:'area',zoomType:'xy',backgroundColor:'#F0F0F0'},credits:{enabled:true,text:"Via ResearchAE.com"},title:{text:chart_title+" - by Month Received",style:{width:'300px'}},subtitle:{text:data.ptreaction_count.total_reports+' adverse event reports | Source: OpenFDA API'+disclaimer},yAxis:{min:0,title:{text:'# Adverse Event Reports'}},xAxis:{type:'category',title:{text:'Month'},labels:{rotation:-45,step:4}},legend:{enabled:false},series:[{name:'Receive Date',data:data.ptreaction_by_receivedate_month.data,}],});}
if($('#drugs-by-reports-graph').length!=0){$('#drugs-by-reports-graph').highcharts({chart:{type:'column',zoomType:'xy',backgroundColor:'#F0F0F0'},credits:{enabled:true,text:"Via ResearchAE.com"},title:{text:chart_title+" - by Drug",style:{width:'300px'}},subtitle:{text:data.drugbrandname_count.total_reports+' adverse event reports | Source: OpenFDA API'+disclaimer},yAxis:{min:0,title:{text:'# Adverse Event Reports'}},xAxis:{type:'category',title:{text:'Drugs'},labels:{enabled:false},minorTickLength:0,tickLength:0},legend:{enabled:true},tooltip:{pointFormat:chart_title+': <b>{point.y}</b>',},series:[{name:'Brand Name',data:data.drugbrandname_count.data,},{name:'Medicinal Product',data:data.medicinalproduct_count.data,}],plotOptions:{series:{cursor:'pointer',point:{events:{click:function(){var search=this.name
var new_location=location.href
if(location.search==""){new_location+="?"}
new_location+="&search="+search
location=new_location}}}}},});}
if($('#manufacturer-by-reports-graph').length!=0){$('#manufacturer-by-reports-graph').highcharts({chart:{type:'column',zoomType:'xy',backgroundColor:'#F0F0F0'},credits:{enabled:true,text:"Via ResearchAE.com"},title:{text:chart_title+" - by Manufacturer",style:{width:'300px'}},subtitle:{text:data.manufacturername_count.total_reports+' adverse event reports | Source: OpenFDA API'+disclaimer},yAxis:{min:0,title:{text:'# Adverse Events'}},xAxis:{type:'category',title:{text:'Manufacturer'},labels:{enabled:false},minorTickLength:0,tickLength:0},legend:{enabled:false},tooltip:{pointFormat:chart_title+': <b>{point.y}</b>',},series:[{name:'Manufacturer',data:data.manufacturername_count.data,}],plotOptions:{series:{cursor:'pointer',point:{events:{click:function(){var manufacturername=this.name
var new_location=location.href
if(location.search==""){new_location+="?"}
new_location+="&manufacturername="+manufacturername
location=new_location}}}}},});}
if($('#qualification-by-reports-graph').length!=0){$('#qualification-by-reports-graph').highcharts({chart:{type:'bar',zoomType:'xy',backgroundColor:'#F0F0F0'},credits:{enabled:true,text:"Via ResearchAE.com"},title:{text:chart_title+" - by Individual Submitting",style:{width:'300px'}},subtitle:{text:data.qualification_count.total_reports+' adverse event reports | Source: OpenFDA API'+disclaimer},yAxis:{min:0,title:{text:'# Adverse Events'}},xAxis:{type:'category',title:{text:'Individual Submitting'},labels:{enabled:true},minorTickLength:0,tickLength:0},legend:{enabled:false},tooltip:{pointFormat:chart_title+': <b>{point.y}</b>',},series:[{name:'Reporter Type',data:data.qualification_count.data,}],});}
if($('#reactions-by-reports-graph').length!=0){$('#reactions-by-reports-graph').highcharts({chart:{type:'column',zoomType:'xy',backgroundColor:'#F0F0F0'},credits:{enabled:true,text:"Via ResearchAE.com"},title:{text:chart_title+" - by Reaction",style:{width:'300px'}},subtitle:{text:data.ptreaction_count.total_events+' adverse events over '+data.ptreaction_count.total_reports+' adverse event reports | Source: OpenFDA API'+disclaimer},yAxis:{min:0,title:{text:'# Adverse Events'}},xAxis:{type:'category',title:{text:'Reactions'},labels:{enabled:false},minorTickLength:0,tickLength:0},legend:{enabled:false},tooltip:{pointFormat:chart_title+': <b>{point.y}</b>',},series:[{name:'Drug Reactions',data:data.ptreaction_count.data,}],plotOptions:{series:{cursor:'pointer',point:{events:{click:function(){var reactionmeddrapt=this.name
var new_location=location.href
if(location.search==""){new_location+="?"}
new_location+="&reactionmeddrapt="+reactionmeddrapt
location=new_location}}}}},});}})})